### ISSUE TITLE
Question about `spotlightOnKeyPressAndHold`

### ISSUE THREAD

**Issue by sammo3182** [mcanouil/quarto-spotlight#3]
The extension is very cool! I have a technical question, though, and hope you can help! I hope to turn on the spotlight when I want rather than every time I click the mouse. I guess this function may relate to the `spotlightOnKeyPressAndHold`. If I am correct, do you mind providing a simple YAML demo of how to set it up? Apologize for not being very familiar with js and keycode settings. Thanks a lot!

**Comment by mcanouil** [comment]
Thanks for using the extension.
Tou can disable the activation on mouse down and setup whatever keyboard key using its code.

For example:

```yaml
spotlight:
  toggleSpotlightOnMouseDown: false
  spotlightOnKeyPressAndHold: 73 # keycode for "i"
```
